// Animation对象
Animation = function Animation(){bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('Animation 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(Animation, "Animation");
Animation.prototype.__proto__=EventTarget.prototype;
Animation.__proto__=EventTarget;
bodavm.toolsFunc.defineProperty(Animation.prototype, "effect", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "startTime", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "currentTime", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "playbackRate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "playState", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "pending", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "id", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "onfinish", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "oncancel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "cancel", {configurable:true, enumerable:true, writable:true, value:function cancel (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "cancel", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "finish", {configurable:true, enumerable:true, writable:true, value:function finish (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "finish", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "pause", {configurable:true, enumerable:true, writable:true, value:function pause (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "pause", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "play", {configurable:true, enumerable:true, writable:true, value:function play (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "play", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "reverse", {configurable:true, enumerable:true, writable:true, value:function reverse (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "reverse", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "updatePlaybackRate", {configurable:true, enumerable:true, writable:true, value:function updatePlaybackRate (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "updatePlaybackRate", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "timeline", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "replaceState", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "onremove", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "finished", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "ready", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "commitStyles", {configurable:true, enumerable:true, writable:true, value:function commitStyles (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "commitStyles", arguments)}},);
bodavm.toolsFunc.defineProperty(Animation.prototype, "persist", {configurable:true, enumerable:true, writable:true, value:function persist (){return bodavm.toolsFunc.dispatch(this, Animation.prototype, "Animation", "persist", arguments)}},);
