// AudioBufferSourceNode对象
AudioBufferSourceNode = function AudioBufferSourceNode(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof AudioBufferSourceNode) ){return bodavm.toolsFunc.throwError("TypeError", "Failed to construct 'AudioBufferSourceNode': 1 argument required, but only 0 present.")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('AudioBufferSourceNode 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(AudioBufferSourceNode, "AudioBufferSourceNode");
AudioBufferSourceNode.prototype.__proto__=AudioScheduledSourceNode.prototype;
AudioBufferSourceNode.__proto__=AudioScheduledSourceNode;
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "buffer", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "playbackRate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "detune", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loop", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loopStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "loopEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(AudioBufferSourceNode.prototype, "start", {configurable:true, enumerable:true, writable:true, value:function start (){return bodavm.toolsFunc.dispatch(this, AudioBufferSourceNode.prototype, "AudioBufferSourceNode", "start", arguments)}},);
