// BackgroundFetchRegistration对象
BackgroundFetchRegistration = function BackgroundFetchRegistration(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof BackgroundFetchRegistration) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('BackgroundFetchRegistration 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(BackgroundFetchRegistration, "BackgroundFetchRegistration");
BackgroundFetchRegistration.prototype.__proto__=EventTarget.prototype;
BackgroundFetchRegistration.__proto__=EventTarget;
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "id", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "uploadTotal", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "uploaded", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "downloadTotal", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "downloaded", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "result", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "failureReason", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "recordsAvailable", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "onprogress", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "abort", {configurable:true, enumerable:true, writable:true, value:function abort (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "abort", arguments)}},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "match", {configurable:true, enumerable:true, writable:true, value:function match (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "match", arguments)}},);
bodavm.toolsFunc.defineProperty(BackgroundFetchRegistration.prototype, "matchAll", {configurable:true, enumerable:true, writable:true, value:function matchAll (){return bodavm.toolsFunc.dispatch(this, BackgroundFetchRegistration.prototype, "BackgroundFetchRegistration", "matchAll", arguments)}},);
