// BluetoothCharacteristicProperties对象
BluetoothCharacteristicProperties = function BluetoothCharacteristicProperties(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof BluetoothCharacteristicProperties) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('BluetoothCharacteristicProperties 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(BluetoothCharacteristicProperties, "BluetoothCharacteristicProperties");
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "broadcast", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "read", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "writeWithoutResponse", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "write", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "notify", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "indicate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "authenticatedSignedWrites", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "reliableWrite", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(BluetoothCharacteristicProperties.prototype, "writableAuxiliaries", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, BluetoothCharacteristicProperties.prototype, "BluetoothCharacteristicProperties", "bodefault_get", arguments)}, set:undefined},);
