// ElementInternals对象
ElementInternals = function ElementInternals(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof ElementInternals) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('ElementInternals 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(ElementInternals, "ElementInternals");
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "form", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "willValidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "validity", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "validationMessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "labels", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "states", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "shadowRoot", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "role", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaAtomic", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaAutoComplete", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBusy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBrailleLabel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaBrailleRoleDescription", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaChecked", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColCount", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColIndex", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaColSpan", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaCurrent", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaDescription", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaDisabled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaExpanded", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaHasPopup", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaHidden", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaInvalid", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaKeyShortcuts", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLabel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLevel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaLive", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaModal", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaMultiLine", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaMultiSelectable", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaOrientation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPlaceholder", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPosInSet", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaPressed", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaReadOnly", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRelevant", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRequired", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRoleDescription", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowCount", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowIndex", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaRowSpan", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSelected", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSetSize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaSort", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueMax", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueMin", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueNow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "ariaValueText", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function checkValidity (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "checkValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function reportValidity (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "reportValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "setFormValue", {configurable:true, enumerable:true, writable:true, value:function setFormValue (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "setFormValue", arguments)}},);
bodavm.toolsFunc.defineProperty(ElementInternals.prototype, "setValidity", {configurable:true, enumerable:true, writable:true, value:function setValidity (){return bodavm.toolsFunc.dispatch(this, ElementInternals.prototype, "ElementInternals", "setValidity", arguments)}},);
