// HTMLFrameSetElement对象
HTMLFrameSetElement = function HTMLFrameSetElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLFrameSetElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLFrameSetElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLFrameSetElement, "HTMLFrameSetElement");
HTMLFrameSetElement.prototype.__proto__=HTMLElement.prototype;
HTMLFrameSetElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "cols", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "rows", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onblur", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onfocus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onresize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onscroll", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onafterprint", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onbeforeprint", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onbeforeunload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onhashchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onlanguagechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onmessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onmessageerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onoffline", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "ononline", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onpagehide", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onpageshow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onpopstate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onrejectionhandled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onstorage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onunhandledrejection", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameSetElement.prototype, "onunload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameSetElement.prototype, "HTMLFrameSetElement", "bodefault_set", arguments)}},);
