// HTMLIFrameElement对象
HTMLIFrameElement = function HTMLIFrameElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLIFrameElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLIFrameElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLIFrameElement, "HTMLIFrameElement");
HTMLIFrameElement.prototype.__proto__=HTMLElement.prototype;
HTMLIFrameElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "src", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "srcdoc", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "sandbox", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allowFullscreen", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "csp", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "featurePolicy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "align", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "scrolling", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "frameBorder", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "longDesc", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "marginHeight", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "marginWidth", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "getSVGDocument", {configurable:true, enumerable:true, writable:true, value:function getSVGDocument (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "getSVGDocument", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "loading", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "allowPaymentRequest", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLIFrameElement.prototype, "credentialless", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLIFrameElement.prototype, "HTMLIFrameElement", "bodefault_set", arguments)}},);
