// HTMLAnchorElement对象
HTMLAnchorElement = function HTMLAnchorElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLAnchorElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLAnchorElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLAnchorElement, "HTMLAnchorElement");
HTMLAnchorElement.prototype.__proto__=HTMLElement.prototype;
HTMLAnchorElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "target", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "download", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "ping", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "rel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "relList", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "hreflang", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "text", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "coords", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "charset", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "rev", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "shape", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "origin", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "protocol", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "username", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "password", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "host", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "hostname", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "port", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "pathname", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "search", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "hash", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "href", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "toString", {configurable:true, enumerable:true, writable:true, value:function toString (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "toString", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAnchorElement.prototype, "hrefTranslate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAnchorElement.prototype, "HTMLAnchorElement", "bodefault_set", arguments)}},);
