// HTMLFrameElement对象
HTMLFrameElement = function HTMLFrameElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLFrameElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLFrameElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLFrameElement, "HTMLFrameElement");
HTMLFrameElement.prototype.__proto__=HTMLElement.prototype;
HTMLFrameElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "scrolling", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "src", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "frameBorder", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "longDesc", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "noResize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "marginHeight", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLFrameElement.prototype, "marginWidth", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLFrameElement.prototype, "HTMLFrameElement", "bodefault_set", arguments)}},);
