// HTMLTextAreaElement对象
HTMLTextAreaElement = function HTMLTextAreaElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLTextAreaElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLTextAreaElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLTextAreaElement, "HTMLTextAreaElement");
HTMLTextAreaElement.prototype.__proto__=HTMLElement.prototype;
HTMLTextAreaElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "autocomplete", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "cols", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "dirName", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "disabled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "form", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "maxLength", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "minLength", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "placeholder", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "readOnly", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "required", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "rows", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "wrap", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "defaultValue", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "value", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "textLength", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "willValidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "validity", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "validationMessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "labels", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "selectionStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "selectionEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "selectionDirection", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function checkValidity (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "checkValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function reportValidity (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "reportValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "select", {configurable:true, enumerable:true, writable:true, value:function select (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "select", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "setCustomValidity", {configurable:true, enumerable:true, writable:true, value:function setCustomValidity (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "setCustomValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "setRangeText", {configurable:true, enumerable:true, writable:true, value:function setRangeText (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "setRangeText", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLTextAreaElement.prototype, "setSelectionRange", {configurable:true, enumerable:true, writable:true, value:function setSelectionRange (){return bodavm.toolsFunc.dispatch(this, HTMLTextAreaElement.prototype, "HTMLTextAreaElement", "setSelectionRange", arguments)}},);
