// HTMLSourceElement对象
HTMLSourceElement = function HTMLSourceElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLSourceElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLSourceElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLSourceElement, "HTMLSourceElement");
HTMLSourceElement.prototype.__proto__=HTMLElement.prototype;
HTMLSourceElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "src", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "srcset", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "sizes", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "media", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLSourceElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLSourceElement.prototype, "HTMLSourceElement", "bodefault_set", arguments)}},);
