// HTMLButtonElement对象
HTMLButtonElement = function HTMLButtonElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLButtonElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLButtonElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLButtonElement, "HTMLButtonElement");
HTMLButtonElement.prototype.__proto__=HTMLElement.prototype;
HTMLButtonElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "disabled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "form", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formAction", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formEnctype", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formMethod", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formNoValidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "formTarget", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "value", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "willValidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "validity", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "validationMessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "labels", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function checkValidity (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "checkValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function reportValidity (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "reportValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "setCustomValidity", {configurable:true, enumerable:true, writable:true, value:function setCustomValidity (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "setCustomValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "popoverTargetElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLButtonElement.prototype, "popoverTargetAction", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLButtonElement.prototype, "HTMLButtonElement", "bodefault_set", arguments)}},);
