// HTMLMarqueeElement对象
HTMLMarqueeElement = function HTMLMarqueeElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLMarqueeElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLMarqueeElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLMarqueeElement, "HTMLMarqueeElement");
HTMLMarqueeElement.prototype.__proto__=HTMLElement.prototype;
HTMLMarqueeElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "behavior", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "bgColor", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "direction", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "hspace", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "loop", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "scrollAmount", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "scrollDelay", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "trueSpeed", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "vspace", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "start", {configurable:true, enumerable:true, writable:true, value:function start (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "start", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLMarqueeElement.prototype, "stop", {configurable:true, enumerable:true, writable:true, value:function stop (){return bodavm.toolsFunc.dispatch(this, HTMLMarqueeElement.prototype, "HTMLMarqueeElement", "stop", arguments)}},);
