// HTMLObjectElement对象
HTMLObjectElement = function HTMLObjectElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLObjectElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLObjectElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLObjectElement, "HTMLObjectElement");
HTMLObjectElement.prototype.__proto__=HTMLElement.prototype;
HTMLObjectElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "data", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "name", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "useMap", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "form", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "contentDocument", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "contentWindow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "willValidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "validity", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "validationMessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "align", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "archive", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "code", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "declare", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "hspace", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "standby", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "vspace", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "codeBase", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "codeType", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "border", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "checkValidity", {configurable:true, enumerable:true, writable:true, value:function checkValidity (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "checkValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "getSVGDocument", {configurable:true, enumerable:true, writable:true, value:function getSVGDocument (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "getSVGDocument", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "reportValidity", {configurable:true, enumerable:true, writable:true, value:function reportValidity (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "reportValidity", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLObjectElement.prototype, "setCustomValidity", {configurable:true, enumerable:true, writable:true, value:function setCustomValidity (){return bodavm.toolsFunc.dispatch(this, HTMLObjectElement.prototype, "HTMLObjectElement", "setCustomValidity", arguments)}},);
