// HTMLBodyElement对象
HTMLBodyElement = function HTMLBodyElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLBodyElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLBodyElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLBodyElement, "HTMLBodyElement");
HTMLBodyElement.prototype.__proto__=HTMLElement.prototype;
HTMLBodyElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "text", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "link", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "vLink", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "aLink", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "bgColor", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "background", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onblur", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onfocus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onresize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onscroll", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onafterprint", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onbeforeprint", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onbeforeunload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onhashchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onlanguagechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onmessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onmessageerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onoffline", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "ononline", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onpagehide", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onpageshow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onpopstate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onrejectionhandled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onstorage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onunhandledrejection", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLBodyElement.prototype, "onunload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLBodyElement.prototype, "HTMLBodyElement", "bodefault_set", arguments)}},);
