// HTMLAreaElement对象
HTMLAreaElement = function HTMLAreaElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof HTMLAreaElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('HTMLAreaElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(HTMLAreaElement, "HTMLAreaElement");
HTMLAreaElement.prototype.__proto__=HTMLElement.prototype;
HTMLAreaElement.__proto__=HTMLElement;
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "alt", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "coords", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "download", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "shape", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "target", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "ping", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "rel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "relList", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "referrerPolicy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "noHref", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "origin", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "protocol", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "username", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "password", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "host", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "hostname", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "port", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "pathname", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "search", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "hash", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "href", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(HTMLAreaElement.prototype, "toString", {configurable:true, enumerable:true, writable:true, value:function toString (){return bodavm.toolsFunc.dispatch(this, HTMLAreaElement.prototype, "HTMLAreaElement", "toString", arguments)}},);
