// MathMLElement对象
MathMLElement = function MathMLElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof MathMLElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('MathMLElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(MathMLElement, "MathMLElement");
MathMLElement.prototype.__proto__=Element.prototype;
MathMLElement.__proto__=Element;
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforexrselect", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onabort", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforeinput", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onblur", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncancel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncanplay", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncanplaythrough", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onclick", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onclose", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextlost", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextmenu", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontextrestored", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncuechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondblclick", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondrag", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragenter", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragleave", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragover", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondragstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondrop", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ondurationchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onemptied", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onended", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onfocus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onformdata", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oninput", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oninvalid", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeydown", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeypress", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onkeyup", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onload", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadeddata", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadedmetadata", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onloadstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousedown", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseenter", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseleave", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousemove", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseout", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseover", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmouseup", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onmousewheel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpause", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onplay", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onplaying", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onprogress", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onratechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onreset", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onresize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onscroll", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onsecuritypolicyviolation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onseeked", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onseeking", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onselect", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onslotchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onstalled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onsubmit", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onsuspend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontimeupdate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontoggle", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onvolumechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwaiting", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationiteration", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkitanimationstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwebkittransitionend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onwheel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onauxclick", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ongotpointercapture", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onlostpointercapture", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerdown", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointermove", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerrawupdate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerup", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointercancel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerover", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerout", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerenter", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpointerleave", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onselectstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onselectionchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationiteration", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onanimationstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionrun", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionstart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitionend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "ontransitioncancel", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncopy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncut", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onpaste", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "dataset", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "nonce", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "autofocus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "tabIndex", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "style", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "attributeStyleMap", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "blur", {configurable:true, enumerable:true, writable:true, value:function blur (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "blur", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "focus", {configurable:true, enumerable:true, writable:true, value:function focus (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "focus", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "oncontentvisibilityautostatechange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onscrollend", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforematch", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(MathMLElement.prototype, "onbeforetoggle", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, MathMLElement.prototype, "MathMLElement", "bodefault_set", arguments)}},);
