// MouseEvent对象
MouseEvent = function MouseEvent(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof MouseEvent) ){return bodavm.toolsFunc.throwError("TypeError", "Failed to construct 'MouseEvent': 1 argument required, but only 0 present.")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('MouseEvent 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(MouseEvent, "MouseEvent");
MouseEvent.prototype.__proto__=UIEvent.prototype;
MouseEvent.__proto__=UIEvent;
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "screenX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "screenY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "clientX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "clientY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "ctrlKey", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "shiftKey", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "altKey", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "metaKey", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "button", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "buttons", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "relatedTarget", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "pageX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "pageY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "x", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "y", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "offsetX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "offsetY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "movementX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "movementY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "fromElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "toElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "layerX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "layerY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "getModifierState", {configurable:true, enumerable:true, writable:true, value:function getModifierState (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "getModifierState", arguments)}},);
bodavm.toolsFunc.defineProperty(MouseEvent.prototype, "initMouseEvent", {configurable:true, enumerable:true, writable:true, value:function initMouseEvent (){return bodavm.toolsFunc.dispatch(this, MouseEvent.prototype, "MouseEvent", "initMouseEvent", arguments)}},);
