// Navigator对象
Navigator = function Navigator(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof Navigator) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('Navigator 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(Navigator, "Navigator");
bodavm.toolsFunc.defineProperty(Navigator.prototype, "vendorSub", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "productSub", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "vendor", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "maxTouchPoints", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "scheduling", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "userActivation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "doNotTrack", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "geolocation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "connection", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "plugins", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "mimeTypes", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "pdfViewerEnabled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "webkitTemporaryStorage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "webkitPersistentStorage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "hardwareConcurrency", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "cookieEnabled", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "appCodeName", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "appName", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "appVersion", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "platform", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "product", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "userAgent", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "language", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "languages", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "onLine", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "webdriver", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "getGamepads", {configurable:true, enumerable:true, writable:true, value:function getGamepads (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "getGamepads", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "javaEnabled", {configurable:true, enumerable:true, writable:true, value:function javaEnabled (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "javaEnabled", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "sendBeacon", {configurable:true, enumerable:true, writable:true, value:function sendBeacon (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "sendBeacon", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "vibrate", {configurable:true, enumerable:true, writable:true, value:function vibrate (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "vibrate", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "bluetooth", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "clipboard", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "credentials", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "keyboard", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "managed", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "mediaDevices", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "storage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "serviceWorker", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "virtualKeyboard", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "wakeLock", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "deviceMemory", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "ink", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "hid", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "locks", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "mediaCapabilities", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "mediaSession", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "permissions", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "presentation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "serial", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "gpu", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "usb", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "windowControlsOverlay", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "xr", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "userAgentData", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "canShare", {configurable:true, enumerable:true, writable:true, value:function canShare (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "canShare", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "share", {configurable:true, enumerable:true, writable:true, value:function share (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "share", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "clearAppBadge", {configurable:true, enumerable:true, writable:true, value:function clearAppBadge (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "clearAppBadge", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "getBattery", {configurable:true, enumerable:true, writable:true, value:function getBattery (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "getBattery", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "getUserMedia", {configurable:true, enumerable:true, writable:true, value:function getUserMedia (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "getUserMedia", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "requestMIDIAccess", {configurable:true, enumerable:true, writable:true, value:function requestMIDIAccess (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "requestMIDIAccess", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "requestMediaKeySystemAccess", {configurable:true, enumerable:true, writable:true, value:function requestMediaKeySystemAccess (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "requestMediaKeySystemAccess", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "setAppBadge", {configurable:true, enumerable:true, writable:true, value:function setAppBadge (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "setAppBadge", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "webkitGetUserMedia", {configurable:true, enumerable:true, writable:true, value:function webkitGetUserMedia (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "webkitGetUserMedia", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "getInstalledRelatedApps", {configurable:true, enumerable:true, writable:true, value:function getInstalledRelatedApps (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "getInstalledRelatedApps", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "registerProtocolHandler", {configurable:true, enumerable:true, writable:true, value:function registerProtocolHandler (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "registerProtocolHandler", arguments)}},);
bodavm.toolsFunc.defineProperty(Navigator.prototype, "unregisterProtocolHandler", {configurable:true, enumerable:true, writable:true, value:function unregisterProtocolHandler (){return bodavm.toolsFunc.dispatch(this, Navigator.prototype, "Navigator", "unregisterProtocolHandler", arguments)}},);
