// PerformanceResourceTiming对象
PerformanceResourceTiming = function PerformanceResourceTiming(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof PerformanceResourceTiming) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('PerformanceResourceTiming 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(PerformanceResourceTiming, "PerformanceResourceTiming");
PerformanceResourceTiming.prototype.__proto__=PerformanceEntry.prototype;
PerformanceResourceTiming.__proto__=PerformanceEntry;
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "initiatorType", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "nextHopProtocol", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "workerStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "redirectStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "redirectEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "fetchStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "domainLookupStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "domainLookupEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "connectStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "connectEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "secureConnectionStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "requestStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "transferSize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "encodedBodySize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "decodedBodySize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "serverTiming", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function toJSON (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "toJSON", arguments)}},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "renderBlockingStatus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceResourceTiming.prototype, "responseStatus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceResourceTiming.prototype, "PerformanceResourceTiming", "bodefault_get", arguments)}, set:undefined},);
