// PerformanceTiming对象
PerformanceTiming = function PerformanceTiming(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof PerformanceTiming) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('PerformanceTiming 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(PerformanceTiming, "PerformanceTiming");
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "navigationStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "unloadEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "unloadEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "redirectStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "redirectEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "fetchStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domainLookupStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domainLookupEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "connectStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "connectEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "secureConnectionStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "requestStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "responseStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "responseEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domLoading", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domInteractive", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domContentLoadedEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domContentLoadedEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "domComplete", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "loadEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "loadEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceTiming.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function toJSON (){return bodavm.toolsFunc.dispatch(this, PerformanceTiming.prototype, "PerformanceTiming", "toJSON", arguments)}},);
