// PerformanceNavigationTiming对象
PerformanceNavigationTiming = function PerformanceNavigationTiming(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof PerformanceNavigationTiming) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('PerformanceNavigationTiming 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(PerformanceNavigationTiming, "PerformanceNavigationTiming");
PerformanceNavigationTiming.prototype.__proto__=PerformanceResourceTiming.prototype;
PerformanceNavigationTiming.__proto__=PerformanceResourceTiming;
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "unloadEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "unloadEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domInteractive", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domContentLoadedEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domContentLoadedEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "domComplete", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "loadEventStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "loadEventEnd", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "redirectCount", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "activationStart", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PerformanceNavigationTiming.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function toJSON (){return bodavm.toolsFunc.dispatch(this, PerformanceNavigationTiming.prototype, "PerformanceNavigationTiming", "toJSON", arguments)}},);
