// PresentationConnection对象
PresentationConnection = function PresentationConnection(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof PresentationConnection) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('PresentationConnection 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(PresentationConnection, "PresentationConnection");
PresentationConnection.prototype.__proto__=EventTarget.prototype;
PresentationConnection.__proto__=EventTarget;
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "id", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "url", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "state", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "onconnect", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "onclose", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "onterminate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "binaryType", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "onmessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function close (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "close", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "send", {configurable:true, enumerable:true, writable:true, value:function send (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "send", arguments)}},);
bodavm.toolsFunc.defineProperty(PresentationConnection.prototype, "terminate", {configurable:true, enumerable:true, writable:true, value:function terminate (){return bodavm.toolsFunc.dispatch(this, PresentationConnection.prototype, "PresentationConnection", "terminate", arguments)}},);
