// RTCDataChannel对象
RTCDataChannel = function RTCDataChannel(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof RTCDataChannel) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('RTCDataChannel 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(RTCDataChannel, "RTCDataChannel");
RTCDataChannel.prototype.__proto__=EventTarget.prototype;
RTCDataChannel.__proto__=EventTarget;
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "label", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "ordered", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "maxPacketLifeTime", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "maxRetransmits", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "protocol", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "negotiated", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "id", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "readyState", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "bufferedAmount", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "bufferedAmountLowThreshold", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onopen", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onbufferedamountlow", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onerror", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onclosing", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onclose", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "onmessage", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "binaryType", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "reliable", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "close", {configurable:true, enumerable:true, writable:true, value:function close (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "close", arguments)}},);
bodavm.toolsFunc.defineProperty(RTCDataChannel.prototype, "send", {configurable:true, enumerable:true, writable:true, value:function send (){return bodavm.toolsFunc.dispatch(this, RTCDataChannel.prototype, "RTCDataChannel", "send", arguments)}},);
