// RTCIceCandidate对象
RTCIceCandidate = function RTCIceCandidate(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof RTCIceCandidate) ){return bodavm.toolsFunc.throwError("TypeError", "Failed to construct 'RTCIceCandidate': sdpMid and sdpMLineIndex are both null.")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('RTCIceCandidate 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(RTCIceCandidate, "RTCIceCandidate");
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "candidate", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "sdpMid", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "sdpMLineIndex", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "foundation", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "component", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "priority", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "address", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "protocol", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "port", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "type", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "tcpType", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "relatedAddress", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "relatedPort", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "usernameFragment", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(RTCIceCandidate.prototype, "toJSON", {configurable:true, enumerable:true, writable:true, value:function toJSON (){return bodavm.toolsFunc.dispatch(this, RTCIceCandidate.prototype, "RTCIceCandidate", "toJSON", arguments)}},);
