// SecurityPolicyViolationEvent对象
SecurityPolicyViolationEvent = function SecurityPolicyViolationEvent(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof SecurityPolicyViolationEvent) ){return bodavm.toolsFunc.throwError("TypeError", "Failed to construct 'SecurityPolicyViolationEvent': 1 argument required, but only 0 present.")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('SecurityPolicyViolationEvent 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(SecurityPolicyViolationEvent, "SecurityPolicyViolationEvent");
SecurityPolicyViolationEvent.prototype.__proto__=Event.prototype;
SecurityPolicyViolationEvent.__proto__=Event;
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "documentURI", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "referrer", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "blockedURI", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "violatedDirective", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "effectiveDirective", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "originalPolicy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "disposition", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "sourceFile", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "statusCode", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "lineNumber", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "columnNumber", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SecurityPolicyViolationEvent.prototype, "sample", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SecurityPolicyViolationEvent.prototype, "SecurityPolicyViolationEvent", "bodefault_get", arguments)}, set:undefined},);
