// ShadowRoot对象
ShadowRoot = function ShadowRoot(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof ShadowRoot) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('ShadowRoot 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(ShadowRoot, "ShadowRoot");
ShadowRoot.prototype.__proto__=DocumentFragment.prototype;
ShadowRoot.__proto__=DocumentFragment;
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "mode", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "host", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "onslotchange", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "innerHTML", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "delegatesFocus", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "slotAssignment", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "pictureInPictureElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "activeElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "styleSheets", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "pointerLockElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "fullscreenElement", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "adoptedStyleSheets", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "elementFromPoint", {configurable:true, enumerable:true, writable:true, value:function elementFromPoint (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "elementFromPoint", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "elementsFromPoint", {configurable:true, enumerable:true, writable:true, value:function elementsFromPoint (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "elementsFromPoint", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "getInnerHTML", {configurable:true, enumerable:true, writable:true, value:function getInnerHTML (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getInnerHTML", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "getSelection", {configurable:true, enumerable:true, writable:true, value:function getSelection (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getSelection", arguments)}},);
bodavm.toolsFunc.defineProperty(ShadowRoot.prototype, "getAnimations", {configurable:true, enumerable:true, writable:true, value:function getAnimations (){return bodavm.toolsFunc.dispatch(this, ShadowRoot.prototype, "ShadowRoot", "getAnimations", arguments)}},);
