// SVGFEDropShadowElement对象
SVGFEDropShadowElement = function SVGFEDropShadowElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof SVGFEDropShadowElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('SVGFEDropShadowElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(SVGFEDropShadowElement, "SVGFEDropShadowElement");
SVGFEDropShadowElement.prototype.__proto__=SVGElement.prototype;
SVGFEDropShadowElement.__proto__=SVGElement;
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "in1", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "dx", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "dy", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "stdDeviationX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "stdDeviationY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "x", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "y", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "result", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDropShadowElement.prototype, "setStdDeviation", {configurable:true, enumerable:true, writable:true, value:function setStdDeviation (){return bodavm.toolsFunc.dispatch(this, SVGFEDropShadowElement.prototype, "SVGFEDropShadowElement", "setStdDeviation", arguments)}},);
