// SVGFEDiffuseLightingElement对象
SVGFEDiffuseLightingElement = function SVGFEDiffuseLightingElement(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof SVGFEDiffuseLightingElement) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('SVGFEDiffuseLightingElement 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(SVGFEDiffuseLightingElement, "SVGFEDiffuseLightingElement");
SVGFEDiffuseLightingElement.prototype.__proto__=SVGElement.prototype;
SVGFEDiffuseLightingElement.__proto__=SVGElement;
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "in1", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "surfaceScale", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "diffuseConstant", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "kernelUnitLengthX", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "kernelUnitLengthY", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "x", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "y", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "width", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "height", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(SVGFEDiffuseLightingElement.prototype, "result", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, SVGFEDiffuseLightingElement.prototype, "SVGFEDiffuseLightingElement", "bodefault_get", arguments)}, set:undefined},);
