// WebTransportDatagramDuplexStream对象
WebTransportDatagramDuplexStream = function WebTransportDatagramDuplexStream(){let arg=arguments[0];
if (arg!='bobo' && !(this instanceof WebTransportDatagramDuplexStream) ){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};bodavm.toolsFunc.symbolProperty(this);
if (arg =='bobo'){console.log_copy('WebTransportDatagramDuplexStream 实例化对象 --->',JSON.stringify_bo(arguments,function(k,v){if (v==window){return 'window'}else{return v}}))};}

bodavm.toolsFunc.safeProto(WebTransportDatagramDuplexStream, "WebTransportDatagramDuplexStream");
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "readable", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "writable", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "maxDatagramSize", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:undefined},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "incomingMaxAge", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "outgoingMaxAge", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "incomingHighWaterMark", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_set", arguments)}},);
bodavm.toolsFunc.defineProperty(WebTransportDatagramDuplexStream.prototype, "outgoingHighWaterMark", {configurable:true, enumerable:true, get:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_get", arguments)}, set:function bodefault (){return bodavm.toolsFunc.dispatch(this, WebTransportDatagramDuplexStream.prototype, "WebTransportDatagramDuplexStream", "bodefault_set", arguments)}},);
