// SVGFEOffsetElement对象
bodavm.memory.globalobj['SVGFEOffsetElement'] = function SVGFEOffsetElement(){if (!(this instanceof SVGFEOffsetElement)){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};this._boisinit=bodavm.config.isinit}
bodavm.toolsFunc.safeProto(bodavm.memory.globalobj['SVGFEOffsetElement'], "SVGFEOffsetElement");
bodavm.memory.globalobj['SVGFEOffsetElement'].prototype.__proto__=bodavm.memory.globalobj['SVGElement'].prototype;
bodavm.memory.globalobj['SVGFEOffsetElement'].__proto__=bodavm.memory.globalobj['SVGElement'];
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "in1", {configurable:true, enumerable:true, get:function in1 (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "in1_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "dx", {configurable:true, enumerable:true, get:function dx (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "dx_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "dy", {configurable:true, enumerable:true, get:function dy (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "dy_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "x", {configurable:true, enumerable:true, get:function x (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "x_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "y", {configurable:true, enumerable:true, get:function y (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "y_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "width", {configurable:true, enumerable:true, get:function width (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "width_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "height", {configurable:true, enumerable:true, get:function height (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "height_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFEOffsetElement', "result", {configurable:true, enumerable:true, get:function result (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFEOffsetElement'].prototype, "SVGFEOffsetElement", "result_get", arguments)}, set:undefined},'prototype');
