// SVGFETileElement对象
bodavm.memory.globalobj['SVGFETileElement'] = function SVGFETileElement(){if (!(this instanceof SVGFETileElement)){return bodavm.toolsFunc.throwError("TypeError", "Illegal constructor")};this._boisinit=bodavm.config.isinit}
bodavm.toolsFunc.safeProto(bodavm.memory.globalobj['SVGFETileElement'], "SVGFETileElement");
bodavm.memory.globalobj['SVGFETileElement'].prototype.__proto__=bodavm.memory.globalobj['SVGElement'].prototype;
bodavm.memory.globalobj['SVGFETileElement'].__proto__=bodavm.memory.globalobj['SVGElement'];
bodavm.toolsFunc.defineProperty('SVGFETileElement', "in1", {configurable:true, enumerable:true, get:function in1 (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "in1_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFETileElement', "x", {configurable:true, enumerable:true, get:function x (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "x_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFETileElement', "y", {configurable:true, enumerable:true, get:function y (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "y_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFETileElement', "width", {configurable:true, enumerable:true, get:function width (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "width_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFETileElement', "height", {configurable:true, enumerable:true, get:function height (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "height_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('SVGFETileElement', "result", {configurable:true, enumerable:true, get:function result (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SVGFETileElement'].prototype, "SVGFETileElement", "result_get", arguments)}, set:undefined},'prototype');
