// SpeechRecognition对象
/*
bodavm.memory.globalobj['SpeechRecognition'] = function SpeechRecognition(){this._boarg= new bodaobj.window.SpeechRecognition();this._boisinit=bodavm.config.isinit}
bodavm.toolsFunc.safeProto(bodavm.memory.globalobj['SpeechRecognition'], "SpeechRecognition");
bodavm.memory.globalobj['SpeechRecognition'].prototype.__proto__=bodavm.memory.globalobj['EventTarget'].prototype;
bodavm.memory.globalobj['SpeechRecognition'].__proto__=bodavm.memory.globalobj['EventTarget'];
bodavm.toolsFunc.defineProperty('SpeechRecognition', "grammars", {configurable:true, enumerable:true, get:function grammars (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "grammars_get", arguments)}, set:function grammars (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "grammars_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "lang", {configurable:true, enumerable:true, get:function lang (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "lang_get", arguments)}, set:function lang (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "lang_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "continuous", {configurable:true, enumerable:true, get:function continuous (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "continuous_get", arguments)}, set:function continuous (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "continuous_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "interimResults", {configurable:true, enumerable:true, get:function interimResults (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "interimResults_get", arguments)}, set:function interimResults (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "interimResults_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "maxAlternatives", {configurable:true, enumerable:true, get:function maxAlternatives (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "maxAlternatives_get", arguments)}, set:function maxAlternatives (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "maxAlternatives_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onaudiostart", {configurable:true, enumerable:true, get:function onaudiostart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onaudiostart_get", arguments)}, set:function onaudiostart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onaudiostart_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onsoundstart", {configurable:true, enumerable:true, get:function onsoundstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onsoundstart_get", arguments)}, set:function onsoundstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onsoundstart_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onspeechstart", {configurable:true, enumerable:true, get:function onspeechstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onspeechstart_get", arguments)}, set:function onspeechstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onspeechstart_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onspeechend", {configurable:true, enumerable:true, get:function onspeechend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onspeechend_get", arguments)}, set:function onspeechend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onspeechend_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onsoundend", {configurable:true, enumerable:true, get:function onsoundend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onsoundend_get", arguments)}, set:function onsoundend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onsoundend_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onaudioend", {configurable:true, enumerable:true, get:function onaudioend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onaudioend_get", arguments)}, set:function onaudioend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onaudioend_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onresult", {configurable:true, enumerable:true, get:function onresult (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onresult_get", arguments)}, set:function onresult (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onresult_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onnomatch", {configurable:true, enumerable:true, get:function onnomatch (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onnomatch_get", arguments)}, set:function onnomatch (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onnomatch_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onerror", {configurable:true, enumerable:true, get:function onerror (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onerror_get", arguments)}, set:function onerror (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onerror_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onstart", {configurable:true, enumerable:true, get:function onstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onstart_get", arguments)}, set:function onstart (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onstart_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "onend", {configurable:true, enumerable:true, get:function onend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onend_get", arguments)}, set:function onend (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "onend_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "abort", {configurable:true, enumerable:true, writable:true, value:function abort (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "abort", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "start", {configurable:true, enumerable:true, writable:true, value:function start (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "start", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('SpeechRecognition', "stop", {configurable:true, enumerable:true, writable:true, value:function stop (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['SpeechRecognition'].prototype, "SpeechRecognition", "stop", arguments)}},'prototype');*/
webkitSpeechRecognition = bodavm.memory.globalobj['SpeechRecognition'];