// Image对象
bodavm.memory.globalobj['Image'] = function Image(){
    if (!(this instanceof Image)) {
        return bodavm.toolsFunc.throwError("TypeError", "Failed to construct 'Image': Please use the 'new' operator, this DOM object constructor cannot be called as a function")
    };

    this._boarg=new bodaobj.window.Image(arguments[0],arguments[1])
}
bodavm.toolsFunc.safeProto(bodavm.memory.globalobj['Image'], "Image");
bodavm.memory.globalobj['Image'].prototype=bodavm.memory.globalobj['HTMLImageElement'].prototype;
bodavm.memory.globalobj['Image'].prototype.__proto__=bodavm.memory.globalobj['HTMLElement'].prototype;
bodavm.toolsFunc.defineProperty('Image', "alt", {configurable:true, enumerable:true, get:function alt (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "alt_get", arguments)}, set:function alt (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "alt_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "src", {configurable:true, enumerable:true, get:function src (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "src_get", arguments)}, set:function src (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "src_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "srcset", {configurable:true, enumerable:true, get:function srcset (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "srcset_get", arguments)}, set:function srcset (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "srcset_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "sizes", {configurable:true, enumerable:true, get:function sizes (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "sizes_get", arguments)}, set:function sizes (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "sizes_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "crossOrigin", {configurable:true, enumerable:true, get:function crossOrigin (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "crossOrigin_get", arguments)}, set:function crossOrigin (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "crossOrigin_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "useMap", {configurable:true, enumerable:true, get:function useMap (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "useMap_get", arguments)}, set:function useMap (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "useMap_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "isMap", {configurable:true, enumerable:true, get:function isMap (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "isMap_get", arguments)}, set:function isMap (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "isMap_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "width", {configurable:true, enumerable:true, get:function width (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "width_get", arguments)}, set:function width (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "width_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "height", {configurable:true, enumerable:true, get:function height (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "height_get", arguments)}, set:function height (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "height_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "naturalWidth", {configurable:true, enumerable:true, get:function naturalWidth (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "naturalWidth_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "naturalHeight", {configurable:true, enumerable:true, get:function naturalHeight (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "naturalHeight_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "complete", {configurable:true, enumerable:true, get:function complete (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "complete_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "currentSrc", {configurable:true, enumerable:true, get:function currentSrc (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "currentSrc_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "referrerPolicy", {configurable:true, enumerable:true, get:function referrerPolicy (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "referrerPolicy_get", arguments)}, set:function referrerPolicy (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "referrerPolicy_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "decoding", {configurable:true, enumerable:true, get:function decoding (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "decoding_get", arguments)}, set:function decoding (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "decoding_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "name", {configurable:true, enumerable:true, get:function name (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "name_get", arguments)}, set:function name (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "name_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "lowsrc", {configurable:true, enumerable:true, get:function lowsrc (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "lowsrc_get", arguments)}, set:function lowsrc (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "lowsrc_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "align", {configurable:true, enumerable:true, get:function align (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "align_get", arguments)}, set:function align (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "align_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "hspace", {configurable:true, enumerable:true, get:function hspace (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "hspace_get", arguments)}, set:function hspace (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "hspace_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "vspace", {configurable:true, enumerable:true, get:function vspace (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "vspace_get", arguments)}, set:function vspace (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "vspace_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "longDesc", {configurable:true, enumerable:true, get:function longDesc (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "longDesc_get", arguments)}, set:function longDesc (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "longDesc_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "border", {configurable:true, enumerable:true, get:function border (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "border_get", arguments)}, set:function border (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "border_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "x", {configurable:true, enumerable:true, get:function x (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "x_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "y", {configurable:true, enumerable:true, get:function y (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "y_get", arguments)}, set:undefined},'prototype');
bodavm.toolsFunc.defineProperty('Image', "decode", {configurable:true, enumerable:true, writable:true, value:function decode (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "decode", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "fetchPriority", {configurable:true, enumerable:true, get:function fetchPriority (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "fetchPriority_get", arguments)}, set:function fetchPriority (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "fetchPriority_set", arguments)}},'prototype');
bodavm.toolsFunc.defineProperty('Image', "loading", {configurable:true, enumerable:true, get:function loading (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "loading_get", arguments)}, set:function loading (){return bodavm.toolsFunc.dispatch(this, bodavm.memory.globalobj['Image'].prototype, "Image", "loading_set", arguments)}},'prototype');
